import type { ContentPageDefinition } from '../../types';
import { GYM_IMAGES, RETAIL_IMAGES } from '../verticalImages';

const IMG_SIDEBAR =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuBn-BCmPvdhaCtvMMugttVWdxIHPK-InLbetXVO24a9ybBlFtbKKa88kuMtsDyNShg-kVTh4ydJJxzjuHH4VJ6Bc08HCUkDKHq9akRSY7XYOEcf_aX2mu1_UOWQT0nopHkjLgHxHpDtNfnxXPKBbHfIZdrLq9jigV-IO7k9lvk8qlXg1dvRDnVNfqIJRXav_hMjCJC52DiBQYXpa_sdLR26lzwHnupS1lFtR2IrbyqFKAOHPQ0tEnS7Osy7Dq8PLpVnHWz-noH3Oyg';
const IMG_INDOOR =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuD-UtwQJzT2m9uIFRyQs3WVXgUnEUfRAaUPE1joG1_4fIa3GmQ45nvKDnH6AEhYwiiPXimScn_LpMiiCQSoUmH-vXeRPYpfYGgSYByL4wEpYfSyFDPFlm01yQoHGrOpe4mNKh9JtIiD4dbfa-DYBeJknXksldv_P96lo8oJw309boOHcPQg3y5RYyQ1l8TGvC0H4Lbf7gdrKqz10zlv1gkWmbvCalPrm_I97_3ajnbKCrJLFB1PR6_1QPnTWKCOsbEmKfKI8xbp6LY';
const IMG_OUTDOOR =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuCDelKvhuDf1eaIuh3VbrI0KaZd6jshkXloQKMXsmus1_gfLrRIc0OrFYVrYvrozrLer8ilYRogaCOWGgaiNm3ftqydqKlm5cA_ltLUC4rfmA9UUoj6xNaFgsbZW14nZT4ApEa0hlY8bAAVeb2LKGs9V8UfqJRhtTl7AyLSHeD1KJdyuZokmf7TLLyAW0VWCIXNDE5SB3Scnav9NLXZ8dr--sAFRHuvTFJ9HorS6LVOvvv3HsD5L4zPsunEFtceG-edIccFBDUAKaA';
const IMG_BAR =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuBHdjyD19lZysABSE7lqFFDnO89QTMq_5hBf4rmivW3z5CMYVLyO1toJwkUr4vBFrRkecWjBu7DUThm49PEU2LMLDUf2GNo5NFklrVZAxQ8FlozJCFGhVpN6xqsaUGbteiFSWEGj-v-VO7VkZgSbphYeH81npt-T89RDlNR2CX5lNTg2i5xq2q-Z4-Sc-nj1YFn9EK3inb3Tfb3Gfwo3px_GbdENWqGzk_30RhjXqAzqq7lXPadJZjMKdw5_QLTticy8dfguoFjmkg';
const IMG_PRIVATE =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuA2pkAsFWKQ41_OMA1ddTgYpa-OaWPSfzKjAc3Riu9meylPu7PiRJpRKfIlxI9cPvho5o2PlQ3mK_s81adzM0XUIPUOrfVBR2RM5BmckG2qHqXQs-_sbaPumWslCXmUBNVwG7bLJfq0dQARIoZ23LIi5P-xbnR_61udb1tcdhXdxqlM499-QD35d4i3mf8mhB5QKaaYqfwiMs87ncXVAhgEfGuRWV4y33tUjUVFwJFY8zYnTSOZAIbn1gB9K9d7HxFK0-0eOHZRjS8';
const IMG_SUMMARY =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuDV5mDLxr2c-NtUDInr3uY8C-1KSK6gkvKT0rDyLyaSxCPb0s1jpJ56QEvz_ZyItQFLHQinnwFHRuusak70kT9l9TvZijJirbJXt4Alm4vkjx_-uOAj27MnkbpSxELFwZXeSnd2Cczuc-sUz78m0yLQ_iHV9NacXPQs7sNLDolPn_aVQvwv012LeCqGAZW7-hL5zmNVB9fjDU8TgL7rwx1g67SxI31wmm7bT9EOeTyhSjNDTp_o9XtM9wcNv7aIcnQtbuYt9QOvjgY';
const IMG_REVIEW =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuBE69CdsxHdMIExbg_I9FWi7Nd48vW4C66in2TTpwKWt4hF_f4Ay18ishqdDIPFD_K_AjWjwaqOVZdkcVlHH_RdigKi-88AuK5JFHEJdIY6jT0c69hn4ysCCHCRkPwtdZhNoNX3oh5L5ZUDz0W7J__FX-Au-pMgzv0u3piZICkSbFYiZ_2osxUT1wW747c4djhVT1DIVVg9ROFQTGPEw2q0fzWS0wR2I-r2a7Srup3NSQ4pkek8Vrd-8-INdq7QfD-GXY-RHYMB7bk';
const IMG_SUCCESS =
  'https://lh3.googleusercontent.com/aida-public/AB6AXuAWpuEh0jxR4sRh2rCDg2H11WiznFzA9IKShr1YUxW3qUCwnBAsQ-Ac-wQGiM5A2EUSVoYJ9yvxUf4bA8cIUBrnYC6pILTHKGV0M1mCDckMTIOh_pHmB3d1gYPXAq0Cn3qpKrdVedhsOcnCqPGsEuK_f9jI93VGUcTBARa4J14lXUx1VkSBk2i6hSZm61CWDElhGNm6st8nDL3LCzQXrxzGWNFTrS6LLdT_PeV01_iC34nvpCVE5w-Iu7kuhFgv3c_tItttapDYy-U';

export const bookingContent: ContentPageDefinition = {
  key: 'booking',
  label: 'Reservations / Booking',
  description:
    'The booking page (tables, classes or appointments). Only the sections for the layout your Booking page uses are shown.',
  previewHash: '#/reservations',
  module: 'booking',
  groups: [
    // ───────────── Layout A - Table reservation ─────────────
    {
      id: 'a_progress',
      title: 'Progress bar',
      description: 'The step counter shown above each step of the reservation.',
      variants: ['a'],
      fields: [
        { key: 'a_step_counter', label: 'Step counter', type: 'text', hint: '{step} and {total} are filled in automatically.' },
        { key: 'a_step1_name', label: 'Step 1 name', type: 'text' },
        { key: 'a_step2_name', label: 'Step 2 name', type: 'text' },
        { key: 'a_step3_name', label: 'Step 3 name', type: 'text' },
        { key: 'a_step4_name', label: 'Step 4 name', type: 'text' },
      ],
    },
    {
      id: 'a_step1',
      title: 'Step 1 - Party size, date & time',
      variants: ['a'],
      fields: [
        { key: 'a_party_heading', label: 'Party size heading', type: 'text' },
        { key: 'a_party_one', label: 'Party size button (1 guest)', type: 'text', hint: '{count} is the number of guests.' },
        { key: 'a_party_many', label: 'Party size button (2+ guests)', type: 'text', hint: '{count} is the number of guests.' },
        { key: 'a_large_group', label: 'Large group button', type: 'text' },
        { key: 'a_date_heading', label: 'Date heading', type: 'text' },
        { key: 'a_time_heading', label: 'Time heading', type: 'text' },
        { key: 'a_afternoon_label', label: 'Afternoon label', type: 'text' },
        { key: 'a_evening_label', label: 'Evening label', type: 'text' },
      ],
    },
    {
      id: 'a_sidebar',
      title: 'Step 1 - Summary card',
      description: 'The card on the right with a photo, your selections and the continue button.',
      variants: ['a'],
      fields: [
        { key: 'a_sidebar_image', label: 'Photo', type: 'image' },
        { key: 'a_sidebar_image_alt', label: 'Photo description (for screen readers)', type: 'text' },
        { key: 'a_sidebar_title', label: 'Title on the photo', type: 'text' },
        { key: 'a_sidebar_guests_label', label: 'Guests label', type: 'text' },
        { key: 'a_people_one', label: 'Guest count (1 person)', type: 'text', hint: '{count} is the number of guests.' },
        { key: 'a_people_many', label: 'Guest count (2+ people)', type: 'text', hint: '{count} is the number of guests.' },
        { key: 'a_sidebar_date_label', label: 'Date label', type: 'text' },
        { key: 'a_sidebar_time_label', label: 'Time label', type: 'text' },
        { key: 'a_time_placeholder', label: 'Shown before a time is picked', type: 'text' },
        { key: 'a_rare_badge', label: 'Highlight badge', type: 'text' },
        { key: 'a_rare_text', label: 'Highlight text', type: 'textarea' },
        { key: 'a_continue_seating', label: 'Continue button', type: 'text' },
      ],
    },
    {
      id: 'a_step2',
      title: 'Step 2 - Seating preference',
      variants: ['a'],
      fields: [
        { key: 'a_seating_heading', label: 'Heading', type: 'text' },
        { key: 'a_seating_subheading', label: 'Subheading', type: 'textarea' },
        {
          key: 'a_seating_options',
          label: 'Seating options',
          type: 'list',
          fixedItems: true,
          hint: 'Leave the badge empty to hide it.',
          itemFields: [
            { key: 'title', label: 'Name', type: 'text' },
            { key: 'badge', label: 'Badge', type: 'text' },
            { key: 'description', label: 'Description', type: 'textarea' },
            { key: 'image', label: 'Photo', type: 'image' },
          ],
        },
        { key: 'a_map_heading', label: 'Floor map heading', type: 'text' },
        { key: 'a_map_show', label: 'Show map button', type: 'text' },
        { key: 'a_map_hide', label: 'Hide map button', type: 'text' },
        { key: 'a_map_outdoor', label: 'Map label - Outdoor', type: 'text' },
        { key: 'a_map_indoor', label: 'Map label - Indoor', type: 'text' },
        { key: 'a_map_bar', label: 'Map label - Bar', type: 'text' },
        { key: 'a_map_private', label: 'Map label - Private', type: 'text' },
        { key: 'a_back_bar', label: 'Back button', type: 'text' },
        { key: 'a_preference_label', label: 'Selected preference label', type: 'text' },
        { key: 'a_preference_empty', label: 'Shown when nothing is selected', type: 'text' },
        { key: 'a_continue_info', label: 'Continue button', type: 'text' },
      ],
    },
    {
      id: 'a_step3',
      title: 'Step 3 - Guest details form',
      variants: ['a'],
      fields: [
        { key: 'a_form_heading', label: 'Heading', type: 'text' },
        { key: 'a_form_subheading', label: 'Subheading', type: 'textarea' },
        { key: 'a_label_name', label: 'Name label', type: 'text' },
        { key: 'a_placeholder_name', label: 'Name placeholder', type: 'text' },
        { key: 'a_label_phone', label: 'Phone label', type: 'text' },
        { key: 'a_placeholder_phone', label: 'Phone placeholder', type: 'text' },
        { key: 'a_label_email', label: 'Email label', type: 'text' },
        { key: 'a_placeholder_email', label: 'Email placeholder', type: 'text' },
        { key: 'a_label_requests', label: 'Special requests label', type: 'text' },
        { key: 'a_placeholder_requests', label: 'Special requests placeholder', type: 'text' },
        { key: 'a_newsletter', label: 'Newsletter checkbox text', type: 'textarea' },
        { key: 'a_terms_before', label: 'Terms checkbox - text before first link', type: 'text' },
        { key: 'a_terms_link', label: 'Terms checkbox - first link', type: 'text' },
        { key: 'a_terms_middle', label: 'Terms checkbox - text between links', type: 'text' },
        { key: 'a_policy_link', label: 'Terms checkbox - second link', type: 'text' },
        { key: 'a_terms_after', label: 'Terms checkbox - text after links', type: 'text' },
        { key: 'a_back', label: 'Back button', type: 'text' },
        { key: 'a_review_button', label: 'Submit button', type: 'text' },
      ],
    },
    {
      id: 'a_step3_summary',
      title: 'Step 3 - Summary card',
      variants: ['a'],
      fields: [
        { key: 'a_summary_image', label: 'Photo', type: 'image' },
        { key: 'a_summary_image_alt', label: 'Photo description (for screen readers)', type: 'text' },
        { key: 'a_summary_heading', label: 'Heading', type: 'text' },
        { key: 'a_summary_datetime_label', label: 'Date & time label', type: 'text' },
        { key: 'a_summary_guests_label', label: 'Guests label', type: 'text' },
        { key: 'a_summary_table_label', label: 'Table type label', type: 'text' },
        { key: 'a_table_default', label: 'Table type when none chosen', type: 'text' },
        { key: 'a_instant_heading', label: 'Guarantee box heading', type: 'text' },
        { key: 'a_instant_text', label: 'Guarantee box text', type: 'textarea' },
      ],
    },
    {
      id: 'a_step4',
      title: 'Step 4 - Review & pay',
      variants: ['a'],
      fields: [
        { key: 'a_review_heading', label: 'Heading', type: 'text' },
        { key: 'a_review_subheading', label: 'Subheading', type: 'text' },
        { key: 'a_review_image', label: 'Photo', type: 'image' },
        { key: 'a_review_image_alt', label: 'Photo description (for screen readers)', type: 'text' },
        { key: 'a_review_badge', label: 'Badge on the photo', type: 'text' },
        { key: 'a_review_title', label: 'Title on the photo', type: 'text' },
        { key: 'a_review_datetime_label', label: 'Date & time label', type: 'text' },
        { key: 'a_review_time', label: 'Time line', type: 'text', hint: '{time} is the chosen time.' },
        { key: 'a_review_party_label', label: 'Party size label', type: 'text' },
        { key: 'a_review_guaranteed', label: 'Guarantee note', type: 'text' },
        { key: 'a_edit_details', label: 'Edit details button', type: 'text' },
        { key: 'a_policy_heading', label: 'Cancellation policy heading', type: 'text' },
        { key: 'a_policy_text', label: 'Cancellation policy text', type: 'textarea' },
        { key: 'a_reminder_text', label: 'Reminder note', type: 'text' },
        { key: 'a_totals_heading', label: 'Totals heading', type: 'text' },
        { key: 'a_booking_fee_label', label: 'Booking fee label', type: 'text' },
        { key: 'a_booking_fee_value', label: 'Booking fee amount', type: 'text' },
        { key: 'a_deposit_label', label: 'Deposit label', type: 'text' },
        { key: 'a_deposit_pending', label: 'Deposit before checkout', type: 'text' },
        { key: 'a_total_label', label: 'Total label', type: 'text' },
        { key: 'a_total_pending', label: 'Total before checkout', type: 'text' },
        { key: 'a_pay_button', label: 'Pay button', type: 'text' },
        { key: 'a_processing', label: 'Pay button while processing', type: 'text' },
        { key: 'a_retry_button', label: 'Retry payment button', type: 'text' },
        { key: 'a_deposit_processing', label: 'Deposit processing note', type: 'textarea' },
        { key: 'a_confirm_terms_before', label: 'Legal note - text before link', type: 'text' },
        { key: 'a_confirm_terms_link', label: 'Legal note - link', type: 'text' },
        { key: 'a_confirm_terms_after', label: 'Legal note - text after link', type: 'text' },
        { key: 'a_vip_heading', label: 'Perk box heading', type: 'text' },
        { key: 'a_vip_text', label: 'Perk box text', type: 'text' },
      ],
    },
    {
      id: 'a_success',
      title: 'Confirmation screen',
      variants: ['a'],
      fields: [
        { key: 'a_success_image', label: 'Background image', type: 'image' },
        { key: 'a_success_heading', label: 'Heading', type: 'text' },
        { key: 'a_success_code_label', label: 'Confirmation code label', type: 'text' },
        { key: 'a_success_sent_before', label: 'Sent-to text - before email', type: 'text' },
        { key: 'a_success_sent_and', label: 'Sent-to text - between email and phone', type: 'text' },
        { key: 'a_success_sent_after', label: 'Sent-to text - after phone', type: 'text' },
        { key: 'a_calendar_heading', label: 'Calendar card heading', type: 'text' },
        { key: 'a_calendar_text', label: 'Calendar card text', type: 'text' },
        { key: 'a_calendar_apple', label: 'Apple button', type: 'text' },
        { key: 'a_calendar_google', label: 'Google button', type: 'text' },
        { key: 'a_calendar_outlook', label: 'Outlook button', type: 'text' },
        { key: 'a_modify_title', label: 'Modify button title', type: 'text' },
        { key: 'a_modify_text', label: 'Modify button text', type: 'text' },
        { key: 'a_cancel_title', label: 'Cancel button title', type: 'text' },
        { key: 'a_cancel_text', label: 'Cancel button text', type: 'text' },
        { key: 'a_back_website', label: 'Back to website button', type: 'text' },
      ],
    },
    {
      id: 'a_messages',
      title: 'Table reservation - messages',
      advanced: true,
      variants: ['a'],
      fields: [
        { key: 'a_prev_month_aria', label: 'Previous month (screen readers)', type: 'text' },
        { key: 'a_next_month_aria', label: 'Next month (screen readers)', type: 'text' },
        { key: 'a_weekday_mo', label: 'Calendar - Monday', type: 'text' },
        { key: 'a_weekday_tu', label: 'Calendar - Tuesday', type: 'text' },
        { key: 'a_weekday_we', label: 'Calendar - Wednesday', type: 'text' },
        { key: 'a_weekday_th', label: 'Calendar - Thursday', type: 'text' },
        { key: 'a_weekday_fr', label: 'Calendar - Friday', type: 'text' },
        { key: 'a_weekday_sa', label: 'Calendar - Saturday', type: 'text' },
        { key: 'a_weekday_su', label: 'Calendar - Sunday', type: 'text' },
        { key: 'a_loading_times', label: 'Loading times', type: 'text' },
        { key: 'a_no_tables', label: 'No tables available', type: 'text' },
        { key: 'a_availability_error', label: 'Times failed to load', type: 'text' },
        { key: 'a_toast_terms', label: 'Terms not accepted', type: 'text' },
        { key: 'a_toast_select_time', label: 'No time selected', type: 'text' },
        { key: 'a_toast_slot_taken', label: 'Time slot taken', type: 'text' },
        { key: 'a_toast_invalid', label: 'Invalid details', type: 'text' },
        { key: 'a_toast_unavailable', label: 'Service unavailable', type: 'text' },
        { key: 'a_toast_confirm_failed', label: 'Reservation failed', type: 'text' },
        { key: 'a_toast_confirmed', label: 'Reservation confirmed', type: 'text', hint: '{code} is the confirmation code.' },
        { key: 'a_toast_apple', label: 'Added to Apple Calendar', type: 'text' },
        { key: 'a_toast_google', label: 'Added to Google Calendar', type: 'text' },
        { key: 'a_toast_outlook', label: 'Added to Outlook Calendar', type: 'text' },
        { key: 'a_cancel_confirm', label: 'Cancel confirmation question', type: 'text' },
        { key: 'a_toast_cancelled', label: 'Reservation cancelled', type: 'text' },
      ],
    },
    {
      id: 'a_payment_messages',
      title: 'Table reservation - payment messages',
      advanced: true,
      variants: ['a'],
      fields: [
        { key: 'a_pay_table_unavailable', label: 'Paid but table unavailable', type: 'textarea' },
        { key: 'a_pay_declined', label: 'Card declined', type: 'text' },
        { key: 'a_pay_still_processing', label: 'Deposit still processing', type: 'text' },
        { key: 'a_pay_failed', label: 'Deposit failed', type: 'text' },
        { key: 'a_pay_retry_failed', label: 'Retry failed', type: 'text' },
      ],
    },

    // ───────────── Layout B - Class timetable ─────────────
    {
      id: 'b_main',
      title: 'Class timetable',
      variants: ['b'],
      fields: [
        { key: 'b_eyebrow', label: 'Small label above heading', type: 'text' },
        { key: 'b_heading', label: 'Heading', type: 'text' },
        { key: 'b_day_heading', label: 'Day picker heading', type: 'text' },
        { key: 'b_sessions_heading', label: 'Sessions heading', type: 'text' },
        { key: 'b_spots_label', label: 'Spots label', type: 'text' },
        { key: 'b_slot_available', label: 'Session has space', type: 'text' },
        { key: 'b_slot_full', label: 'Session is full', type: 'text' },
        { key: 'b_details_heading', label: 'Details heading', type: 'text' },
        { key: 'b_placeholder_name', label: 'Name placeholder', type: 'text' },
        { key: 'b_placeholder_email', label: 'Email placeholder', type: 'text' },
        { key: 'b_placeholder_phone', label: 'Phone placeholder', type: 'text' },
        { key: 'b_submit', label: 'Book button', type: 'text' },
      ],
    },
    {
      id: 'b_success',
      title: 'Class booked screen',
      variants: ['b'],
      fields: [
        { key: 'b_success_heading', label: 'Heading', type: 'text' },
        { key: 'b_success_when', label: 'Time & date line', type: 'text', hint: '{time} and {date} are filled in automatically.' },
        { key: 'b_success_code_label', label: 'Confirmation code label', type: 'text' },
        { key: 'b_back_website', label: 'Back to website button', type: 'text' },
      ],
    },
    {
      id: 'b_messages',
      title: 'Class timetable - messages',
      advanced: true,
      variants: ['b'],
      fields: [
        { key: 'b_loading', label: 'Loading sessions', type: 'text' },
        { key: 'b_empty', label: 'No sessions that day', type: 'text' },
        { key: 'b_toast_booked', label: 'Session booked', type: 'text', hint: '{code} is the confirmation code.' },
        { key: 'b_toast_failed', label: 'Booking failed', type: 'text' },
      ],
    },

    // ───────────── Layout C - Appointments ─────────────
    {
      id: 'c_main',
      title: 'Appointment booking',
      variants: ['c'],
      fields: [
        { key: 'c_eyebrow', label: 'Small label above heading', type: 'text' },
        { key: 'c_heading', label: 'Heading', type: 'text' },
        { key: 'c_service_heading', label: 'Service picker heading', type: 'text' },
        {
          key: 'c_services',
          label: 'Services',
          type: 'list',
          hint: 'Duration and description are optional and only shown when filled in.',
          itemFields: [
            { key: 'name', label: 'Name', type: 'text' },
            { key: 'duration', label: 'Duration', type: 'text' },
            { key: 'description', label: 'Description', type: 'textarea' },
          ],
        },
        { key: 'c_datetime_heading', label: 'Date & time heading', type: 'text' },
        { key: 'c_details_heading', label: 'Details heading', type: 'text' },
        { key: 'c_placeholder_name', label: 'Name placeholder', type: 'text' },
        { key: 'c_placeholder_email', label: 'Email placeholder', type: 'text' },
        { key: 'c_placeholder_phone', label: 'Phone placeholder', type: 'text' },
        { key: 'c_placeholder_notes', label: 'Notes placeholder', type: 'text' },
        { key: 'c_submit', label: 'Book button', type: 'text' },
      ],
    },
    {
      id: 'c_success',
      title: 'Appointment booked screen',
      variants: ['c'],
      fields: [
        { key: 'c_success_heading', label: 'Heading', type: 'text' },
        { key: 'c_success_when', label: 'Service, time & date line', type: 'text', hint: '{service}, {time} and {date} are filled in automatically.' },
        { key: 'c_success_code_label', label: 'Confirmation code label', type: 'text' },
        { key: 'c_back_website', label: 'Back to website button', type: 'text' },
      ],
    },
    {
      id: 'c_messages',
      title: 'Appointment booking - messages',
      advanced: true,
      variants: ['c'],
      fields: [
        { key: 'c_loading', label: 'Loading times', type: 'text' },
        { key: 'c_empty', label: 'No availability that day', type: 'text' },
        { key: 'c_no_services', label: 'No services listed', type: 'text' },
        { key: 'c_toast_booked', label: 'Appointment booked', type: 'text', hint: '{code} is the confirmation code.' },
        { key: 'c_toast_failed', label: 'Booking failed', type: 'text' },
      ],
    },
  ],
  defaults: {
    // Layout A - progress
    a_step_counter: 'Step {step} of {total}',
    a_step1_name: 'SELECT DETAILS',
    a_step2_name: 'SEATING PREFERENCE',
    a_step3_name: 'GUEST INFORMATION',
    a_step4_name: 'FINAL REVIEW',
    // Layout A - step 1
    a_party_heading: 'Party Size',
    a_party_one: '{count} Guest',
    a_party_many: '{count} Guests',
    a_large_group: 'Large Group (8+)',
    a_date_heading: 'Date',
    a_time_heading: 'Available Time',
    a_afternoon_label: 'Afternoon',
    a_evening_label: 'Evening',
    // Layout A - step 1 sidebar
    a_sidebar_image: IMG_SIDEBAR,
    a_sidebar_image_alt: '{brand} Fine Dining Plating',
    a_sidebar_title: '{brand} {city}',
    a_sidebar_guests_label: 'Guests',
    a_people_one: '{count} Person',
    a_people_many: '{count} People',
    a_sidebar_date_label: 'Date',
    a_sidebar_time_label: 'Time',
    a_time_placeholder: 'Select a time',
    a_rare_badge: 'RARE FIND',
    a_rare_text: 'This time slot is in high demand. We recommend booking soon to secure your experience.',
    a_continue_seating: 'Continue to Seating',
    // Layout A - step 2
    a_seating_heading: 'Where would you like to sit?',
    a_seating_subheading:
      'Select your preferred environment for an unforgettable culinary experience tailored to your mood.',
    a_seating_options: [
      { id: 'Indoor', title: 'Indoor', badge: 'POPULAR', description: 'The elegant main hall with curated art and soft acoustics.', image: IMG_INDOOR },
      { id: 'Outdoor', title: 'Outdoor', badge: '', description: 'Breezy terrace dining with panoramic garden views.', image: IMG_OUTDOOR },
      { id: 'The Bar', title: 'The Bar', badge: '', description: 'High-energy seating near our award-winning mixologists.', image: IMG_BAR },
      { id: 'Private', title: 'Private', badge: 'VIP', description: 'Intimate booths or rooms for focused conversation.', image: IMG_PRIVATE },
    ],
    a_map_heading: 'Floor Map Visualization',
    a_map_show: 'VIEW MAP',
    a_map_hide: 'HIDE MAP',
    a_map_outdoor: 'OUTDOOR',
    a_map_indoor: 'INDOOR HALL',
    a_map_bar: 'THE BAR',
    a_map_private: 'PRIVATE',
    a_back_bar: 'BACK',
    a_preference_label: 'PREFERENCE',
    a_preference_empty: 'Please select an option',
    a_continue_info: 'Continue to Information',
    // Layout A - step 3
    a_form_heading: 'Secure Your Table',
    a_form_subheading: "Please provide your details to finalize the reservation. We'll send a confirmation to your email.",
    a_label_name: 'FULL NAME',
    a_placeholder_name: 'Julianne Smith',
    a_label_phone: 'PHONE NUMBER',
    a_placeholder_phone: '+44 20 7123 4567',
    a_label_email: 'EMAIL ADDRESS',
    a_placeholder_email: 'julianne.s@example.com',
    a_label_requests: 'SPECIAL REQUESTS (ANNIVERSARY, ALLERGIES, ETC.)',
    a_placeholder_requests: 'Is there anything we should know about your visit?',
    a_newsletter: 'Send me occasional updates, seasonal menu previews, and exclusive offers (Newsletter).',
    a_terms_before: 'I agree to the',
    a_terms_link: 'Terms of Service',
    a_terms_middle: 'and',
    a_policy_link: 'Cancellation Policy',
    a_terms_after: '.',
    a_back: 'Back',
    a_review_button: 'Review Reservation',
    // Layout A - step 3 summary
    a_summary_image: IMG_SUMMARY,
    a_summary_image_alt: 'Scallop Gourmet Dish',
    a_summary_heading: 'Reservation Summary',
    a_summary_datetime_label: 'DATE & TIME',
    a_summary_guests_label: 'GUESTS',
    a_summary_table_label: 'TABLE TYPE',
    a_table_default: 'Main Dining Area',
    a_instant_heading: 'Instant Confirmation',
    a_instant_text: '{brand} guarantees your table immediately upon booking. No waiting lists or secondary approvals required.',
    // Layout A - step 4
    a_review_heading: 'Almost there.',
    a_review_subheading: 'Please review your reservation details before confirming.',
    a_review_image: IMG_REVIEW,
    a_review_image_alt: '{brand} Interior Dining Room',
    a_review_badge: 'CONFIRMED RESTAURANT',
    a_review_title: '{brand}',
    a_review_datetime_label: 'Date & Time',
    a_review_time: 'at {time}',
    a_review_party_label: 'Party Size',
    a_review_guaranteed: 'Seating Guaranteed',
    a_edit_details: 'Edit Details',
    a_policy_heading: 'Cancellation Policy',
    a_policy_text:
      'Reservation deposits are charged when the booking is confirmed. Automatic refunds are not available in this release; please contact the restaurant before cancelling if you need assistance.',
    a_reminder_text: "We'll send you a reminder 48 hours before your booking.",
    a_totals_heading: 'Reservation Summary',
    a_booking_fee_label: 'Booking Fee',
    a_booking_fee_value: '$0.00',
    a_deposit_label: 'Reservation Deposit',
    a_deposit_pending: 'Calculated at checkout',
    a_total_label: 'Total',
    a_total_pending: '—',
    a_pay_button: 'Continue to Card Payment',
    a_processing: 'Processing...',
    a_retry_button: 'Retry with another card',
    a_deposit_processing: 'Deposit processing. This page will update when Finix confirms the result.',
    a_confirm_terms_before: 'By clicking confirm, you agree to our',
    a_confirm_terms_link: 'Terms of Service',
    a_confirm_terms_after: '.',
    a_vip_heading: 'VIP ACCESSIBILITY',
    a_vip_text: 'Member rewards apply at check-in.',
    // Layout A - success
    a_success_image: IMG_SUCCESS,
    a_success_heading: 'Your table is reserved!',
    a_success_code_label: 'Confirmation ID:',
    a_success_sent_before: 'A confirmation has been sent to',
    a_success_sent_and: 'and',
    a_success_sent_after: '.',
    a_calendar_heading: 'Add to Calendar',
    a_calendar_text: "Ensure you don't miss the moment.",
    a_calendar_apple: 'Apple',
    a_calendar_google: 'Google',
    a_calendar_outlook: 'Outlook',
    a_modify_title: 'Modify Reservation',
    a_modify_text: 'Change time or party size',
    a_cancel_title: 'Cancel Reservation',
    a_cancel_text: 'No longer able to attend?',
    a_back_website: 'Back to Website',
    // Layout A - messages
    a_prev_month_aria: 'Previous month',
    a_next_month_aria: 'Next month',
    a_weekday_mo: 'Mo',
    a_weekday_tu: 'Tu',
    a_weekday_we: 'We',
    a_weekday_th: 'Th',
    a_weekday_fr: 'Fr',
    a_weekday_sa: 'Sa',
    a_weekday_su: 'Su',
    a_loading_times: 'Loading available times…',
    a_no_tables: 'No tables are available for this date and party size.',
    a_availability_error: 'Unable to load available times. Please try again.',
    a_toast_terms: 'Please agree to the Terms of Service to continue',
    a_toast_select_time: 'Please select an available time before confirming your reservation.',
    a_toast_slot_taken: 'That time slot is no longer available. Please choose another time.',
    a_toast_invalid: 'Please check your reservation details and try again.',
    a_toast_unavailable: 'The reservation service is temporarily unavailable. Please try again shortly.',
    a_toast_confirm_failed: 'Unable to confirm your reservation. Please try again.',
    a_toast_confirmed: 'Reservation confirmed! Code: {code}',
    a_toast_apple: 'Added to Apple Calendar',
    a_toast_google: 'Added to Google Calendar',
    a_toast_outlook: 'Added to Outlook Calendar',
    a_cancel_confirm: 'Are you sure you wish to cancel this reservation?',
    a_toast_cancelled: 'Reservation cancelled',
    // Layout A - payment messages
    a_pay_table_unavailable:
      'Your payment succeeded, but the selected table became unavailable. Please contact the restaurant with this payment reference so staff can assist you.',
    a_pay_declined: 'Your card was declined. You can retry with another card.',
    a_pay_still_processing: 'Your deposit is still processing. Please keep this page open and check again shortly.',
    a_pay_failed: 'Unable to process the reservation deposit.',
    a_pay_retry_failed: 'Unable to retry this payment.',

    // Layout B
    b_eyebrow: 'Book a Session',
    b_heading: 'Weekly Timetable',
    b_day_heading: 'Choose a day',
    b_sessions_heading: 'Available sessions',
    b_spots_label: 'Spots',
    b_slot_available: 'Spots available',
    b_slot_full: 'Full',
    b_details_heading: 'Your details',
    b_placeholder_name: 'Full name',
    b_placeholder_email: 'Email',
    b_placeholder_phone: 'Phone',
    b_submit: 'Confirm booking',
    b_success_heading: "You're booked in!",
    b_success_when: '{time} on {date}',
    b_success_code_label: 'Confirmation code:',
    b_back_website: 'Back to website',
    b_loading: 'Loading sessions…',
    b_empty: 'No sessions scheduled for this day.',
    b_toast_booked: 'Session booked! Code: {code}',
    b_toast_failed: 'Unable to book this session. Please try again.',

    // Layout C
    c_eyebrow: 'Book an Appointment',
    c_heading: 'Choose a service',
    c_service_heading: 'Service',
    c_services: [
      { id: 'personal-styling', name: 'Personal Styling', duration: '', description: '' },
      { id: 'fitting-consultation', name: 'Fitting Consultation', duration: '', description: '' },
      { id: 'product-demo', name: 'Product Demo', duration: '', description: '' },
      { id: 'general-inquiry', name: 'General Inquiry', duration: '', description: '' },
    ],
    c_datetime_heading: 'Date & time',
    c_details_heading: 'Your details',
    c_placeholder_name: 'Full name',
    c_placeholder_email: 'Email',
    c_placeholder_phone: 'Phone',
    c_placeholder_notes: 'Anything we should know?',
    c_submit: 'Confirm appointment',
    c_success_heading: 'Appointment confirmed',
    c_success_when: '{service} · {time} on {date}',
    c_success_code_label: 'Confirmation code:',
    c_back_website: 'Back to website',
    c_loading: 'Loading available times…',
    c_empty: 'No availability on this date.',
    c_no_services: 'No services are available to book right now.',
    c_toast_booked: 'Appointment booked! Code: {code}',
    c_toast_failed: 'Unable to book this appointment. Please try again.',
  },
  // Layout A is a restaurant table booking by design. These keep it right if a Gym or Retail Site picks it -
  // same seating-option ids (the booking payload uses them), different words and photos.
  verticalDefaults: {
    gym: {
      a_step1_name: 'SELECT CLASS',
      a_step2_name: 'TRAINING AREA',
      a_step3_name: 'YOUR DETAILS',
      a_party_heading: 'Spots',
      a_party_one: '{count} Spot',
      a_party_many: '{count} Spots',
      a_large_group: 'Group Booking (8+)',
      a_time_heading: 'Class Times',
      a_afternoon_label: 'Daytime',
      a_evening_label: 'Evening',
      a_sidebar_image: GYM_IMAGES.floor,
      a_sidebar_image_alt: 'The {brand} training floor',
      a_sidebar_title: '{brand}',
      a_sidebar_guests_label: 'Spots',
      a_rare_badge: 'FILLING FAST',
      a_rare_text: 'This class is popular. Book now to secure your spot.',
      a_continue_seating: 'Continue to Training Area',
      a_seating_heading: 'Where would you like to train?',
      a_seating_subheading: 'Pick the space that suits your session.',
      a_seating_options: [
        { id: 'Indoor', title: 'Main Floor', badge: 'POPULAR', description: 'Racks, platforms and free weights - our busiest space.', image: GYM_IMAGES.barbell },
        { id: 'Outdoor', title: 'Outdoor Deck', badge: '', description: 'Conditioning and ropes in the open air.', image: GYM_IMAGES.ropes },
        { id: 'The Bar', title: 'Studio', badge: '', description: 'Mat classes, Pilates and mobility in a calm room.', image: GYM_IMAGES.matClass },
        { id: 'Private', title: 'Private Coaching', badge: '1:1', description: 'A dedicated corner with your coach.', image: GYM_IMAGES.dumbbell },
      ],
      a_map_heading: 'Studio Map',
      a_map_outdoor: 'OUTDOOR DECK',
      a_map_indoor: 'MAIN FLOOR',
      a_map_bar: 'STUDIO',
      a_map_private: 'PRIVATE',
      a_continue_info: 'Continue to Your Details',
      a_form_heading: 'Secure Your Spot',
      a_form_subheading: "Add your details to confirm your booking. We'll email you a confirmation.",
      a_placeholder_name: 'Alex Morgan',
      a_placeholder_phone: '+1 (312) 555-0100',
      a_placeholder_email: 'alex@example.com',
      a_label_requests: 'NOTES FOR YOUR COACH (INJURIES, GOALS, ETC.)',
      a_placeholder_requests: 'Anything your coach should know?',
      a_newsletter: 'Send me class updates, new programs and member offers (Newsletter).',
      a_review_button: 'Review Booking',
      a_summary_image: GYM_IMAGES.matClass,
      a_summary_image_alt: 'A {brand} class',
      a_summary_heading: 'Booking Summary',
      a_summary_guests_label: 'SPOTS',
      a_summary_table_label: 'TRAINING AREA',
      a_table_default: 'Main Floor',
      a_instant_text: '{brand} confirms your spot instantly. No waiting lists or approvals.',
      a_review_subheading: 'Please review your booking before confirming.',
      a_review_image: GYM_IMAGES.studio,
      a_review_image_alt: 'Inside {brand}',
      a_review_badge: 'CONFIRMED STUDIO',
      a_review_party_label: 'Spots',
      a_review_guaranteed: 'Spot Guaranteed',
      a_policy_text: 'Booking deposits are charged when your spot is confirmed. Please contact the studio before cancelling if you need help.',
      a_reminder_text: "We'll remind you 24 hours before your class.",
      a_totals_heading: 'Booking Summary',
      a_deposit_label: 'Booking Deposit',
      a_vip_text: 'Member perks apply at check-in.',
      a_success_image: GYM_IMAGES.floor,
      a_success_heading: 'Your spot is booked!',
      a_modify_title: 'Modify Booking',
      a_modify_text: 'Change class time or spots',
      a_cancel_title: 'Cancel Booking',
      a_cancel_text: 'Can no longer make it?',
      a_no_tables: 'No spots are available for this class and group size.',
      a_toast_select_time: 'Please select a class time before confirming your booking.',
      a_toast_slot_taken: 'That class is now full. Please choose another time.',
      a_toast_confirmed: 'Booking confirmed! Code: {code}',
      a_cancel_confirm: 'Are you sure you wish to cancel this booking?',
      a_toast_cancelled: 'Booking cancelled',
      a_pay_table_unavailable: 'Your payment succeeded, but the class filled up. Please contact the studio with this payment reference so staff can help.',
    },
    retail: {
      a_step1_name: 'SELECT A TIME',
      a_step2_name: 'APPOINTMENT TYPE',
      a_step3_name: 'YOUR DETAILS',
      a_party_heading: 'Visitors',
      a_party_one: '{count} Visitor',
      a_party_many: '{count} Visitors',
      a_large_group: 'Group Visit (8+)',
      a_time_heading: 'Available Times',
      a_afternoon_label: 'Daytime',
      a_evening_label: 'Evening',
      a_sidebar_image: RETAIL_IMAGES.shop,
      a_sidebar_image_alt: 'The {brand} shop',
      a_sidebar_title: '{brand}',
      a_sidebar_guests_label: 'Visitors',
      a_rare_badge: 'POPULAR TIME',
      a_rare_text: 'This time books up quickly. Reserve now to secure your appointment.',
      a_continue_seating: 'Continue to Appointment Type',
      a_seating_heading: 'What kind of appointment?',
      a_seating_subheading: 'Choose how you would like to shop with us.',
      a_seating_options: [
        { id: 'Indoor', title: 'In-store Visit', badge: 'POPULAR', description: 'Browse the shop floor with a team member on hand.', image: RETAIL_IMAGES.shop },
        { id: 'Outdoor', title: 'Curbside Pickup', badge: '', description: 'We bring your order out to you.', image: RETAIL_IMAGES.cups },
        { id: 'The Bar', title: 'Styling Session', badge: '', description: 'One-to-one help putting a look or a room together.', image: RETAIL_IMAGES.armchair },
        { id: 'Private', title: 'Private Appointment', badge: 'VIP', description: 'The shop to yourself, before or after hours.', image: RETAIL_IMAGES.livingRoom },
      ],
      a_map_heading: 'Store Map',
      a_map_outdoor: 'PICKUP',
      a_map_indoor: 'SHOP FLOOR',
      a_map_bar: 'STYLING',
      a_map_private: 'PRIVATE',
      a_continue_info: 'Continue to Your Details',
      a_form_heading: 'Book Your Appointment',
      a_form_subheading: "Add your details to confirm. We'll email you a confirmation.",
      a_placeholder_name: 'Jordan Lee',
      a_placeholder_phone: '+1 (415) 555-0100',
      a_placeholder_email: 'jordan@example.com',
      a_label_requests: 'WHAT ARE YOU LOOKING FOR?',
      a_placeholder_requests: 'Sizes, styles or items you would like us to have ready.',
      a_newsletter: 'Send me new arrivals, restocks and exclusive offers (Newsletter).',
      a_review_button: 'Review Appointment',
      a_summary_image: RETAIL_IMAGES.plates,
      a_summary_image_alt: 'Products at {brand}',
      a_summary_heading: 'Appointment Summary',
      a_summary_guests_label: 'VISITORS',
      a_summary_table_label: 'APPOINTMENT TYPE',
      a_table_default: 'In-store Visit',
      a_instant_text: '{brand} confirms your appointment instantly. No waiting lists or approvals.',
      a_review_subheading: 'Please review your appointment before confirming.',
      a_review_image: RETAIL_IMAGES.livingRoom,
      a_review_image_alt: 'Inside {brand}',
      a_review_badge: 'CONFIRMED STORE',
      a_review_party_label: 'Visitors',
      a_review_guaranteed: 'Appointment Guaranteed',
      a_policy_text: 'Appointment deposits are charged when your booking is confirmed. Please contact the shop before cancelling if you need help.',
      a_reminder_text: "We'll send you a reminder 24 hours before your appointment.",
      a_totals_heading: 'Appointment Summary',
      a_deposit_label: 'Appointment Deposit',
      a_vip_text: 'Loyalty perks apply in store.',
      a_success_image: RETAIL_IMAGES.shop,
      a_success_heading: 'Your appointment is booked!',
      a_modify_title: 'Modify Appointment',
      a_modify_text: 'Change the time or number of visitors',
      a_cancel_title: 'Cancel Appointment',
      a_cancel_text: 'Can no longer make it?',
      a_no_tables: 'No appointments are available for this date.',
      a_toast_select_time: 'Please select a time before confirming your appointment.',
      a_toast_slot_taken: 'That time is no longer available. Please choose another.',
      a_toast_confirmed: 'Appointment confirmed! Code: {code}',
      a_cancel_confirm: 'Are you sure you wish to cancel this appointment?',
      a_toast_cancelled: 'Appointment cancelled',
      a_pay_table_unavailable: 'Your payment succeeded, but the time became unavailable. Please contact the shop with this payment reference so staff can help.',
    },
  },
};
