import type { ContentPageDefinition } from '../../types';

/** Online Order page (#/menu). Keys prefixed `a_`/`b_`/`c_` belong to that Catalog layout only. */
export const catalogContent: ContentPageDefinition = {
  key: 'catalog',
  label: 'Online Order (Catalog)',
  description: 'The page where customers browse your items and add them to their order.',
  previewHash: '#/menu',
  module: 'catalog',
  groups: [
    // ---- Variant A - Menu Grid ----
    {
      id: 'a_header',
      title: 'Page header',
      description: 'The banner at the top of the order page.',
      variants: ['a'],
      fields: [
        { key: 'a_eyebrow', label: 'Small heading above the title', type: 'text' },
        { key: 'a_title', label: 'Title', type: 'text', hint: '{brand} is replaced with your business name.' },
        { key: 'a_rating', label: 'Rating', type: 'text', hint: '{avgRating} is the average rating of your items. Leave empty to hide the rating.' },
        { key: 'a_reviews', label: 'Reviews text', type: 'text', hint: '{reviewCount} is the total number of reviews across your items.' },
        { key: 'a_cuisine', label: 'Style / speciality', type: 'text', hint: '{cuisine} uses the cuisine or tagline from your business information. Leave empty to hide.' },
        { key: 'a_prepTime', label: 'Detail 1 (e.g. preparation or session time)', type: 'text', hint: 'Leave empty to hide.' },
        { key: 'a_prepTimeIcon', label: 'Detail 1 icon', type: 'text', hint: 'A Material Symbols name, e.g. "schedule".' },
        { key: 'a_pickup', label: 'Detail 2 (e.g. pickup or delivery note)', type: 'text', hint: 'Leave empty to hide.' },
        { key: 'a_pickupIcon', label: 'Detail 2 icon', type: 'text', hint: 'A Material Symbols name, e.g. "shopping_bag".' },
      ],
    },
    {
      id: 'a_sections',
      title: 'Sections',
      description: 'The page shows a "Popular" section, then one section per category - in the order set under Categories.',
      variants: ['a'],
      fields: [
        { key: 'a_popularHeading', label: 'Popular section heading', type: 'text' },
        { key: 'a_popularSubheading', label: 'Popular section side note', type: 'text' },
        { key: 'a_sidebarTitle', label: 'Side menu title', type: 'text' },
      ],
    },
    {
      id: 'a_filters',
      title: 'Search & filters',
      variants: ['a'],
      fields: [
        { key: 'a_searchPlaceholder', label: 'Search box placeholder', type: 'text' },
        { key: 'a_filterPopular', label: '"Popular" filter', type: 'text' },
        { key: 'a_filterVeg', label: '"Vegetarian" filter', type: 'text', hint: 'Only shown when your items are marked veg / non-veg.' },
        { key: 'a_filterNonVeg', label: '"Non-vegetarian" filter', type: 'text', hint: 'Only shown when your items are marked veg / non-veg.' },
        { key: 'a_emptyTitle', label: 'No results - title', type: 'text' },
        { key: 'a_emptyText', label: 'No results - message', type: 'text' },
        { key: 'a_cartTitle', label: 'Order bar title', type: 'text', hint: 'Shown at the bottom of the screen once something is in the order.' },
      ],
    },
    {
      id: 'a_labels',
      title: 'Buttons & messages',
      advanced: true,
      variants: ['a'],
      fields: [
        { key: 'a_addButton', label: 'Add button', type: 'text' },
        { key: 'a_addAnotherAria', label: '"Add another" button (screen readers)', type: 'text' },
        { key: 'a_shareButton', label: 'Share button', type: 'text' },
        { key: 'a_shareToast', label: 'Message after sharing', type: 'text' },
        { key: 'a_favoriteButton', label: 'Favorite button', type: 'text' },
        { key: 'a_favoritedButton', label: 'Favorite button (once favorited)', type: 'text' },
        { key: 'a_favoriteAddedToast', label: 'Message when added to favorites', type: 'text' },
        { key: 'a_favoriteRemovedToast', label: 'Message when removed from favorites', type: 'text' },
      ],
    },

    // ---- Variant B - Program Schedule ----
    {
      id: 'b_header',
      title: 'Page header & schedule',
      variants: ['b'],
      fields: [
        { key: 'b_eyebrow', label: 'Small heading above the title', type: 'text' },
        { key: 'b_title', label: 'Title', type: 'text' },
        { key: 'b_searchPlaceholder', label: 'Search box placeholder', type: 'text' },
        { key: 'b_cartTitle', label: 'Order bar title', type: 'text', hint: 'Shown at the bottom of the screen once something is selected.' },
      ],
    },
    {
      id: 'b_labels',
      title: 'Buttons & counts',
      advanced: true,
      variants: ['b'],
      fields: [
        { key: 'b_addButton', label: 'Book button', type: 'text' },
        { key: 'b_sessionCount', label: 'Number of sessions in a group', type: 'text', hint: '{count} is replaced with the number.' },
      ],
    },

    // ---- Variant C - Product List ----
    {
      id: 'c_header',
      title: 'Page header & list',
      variants: ['c'],
      fields: [
        { key: 'c_eyebrow', label: 'Small heading above the title', type: 'text' },
        { key: 'c_title', label: 'Title', type: 'text' },
        { key: 'c_searchPlaceholder', label: 'Search box placeholder', type: 'text' },
        { key: 'c_allCategories', label: '"All categories" option', type: 'text' },
        { key: 'c_emptyText', label: 'No results message', type: 'text' },
        { key: 'c_cartTitle', label: 'Order bar title', type: 'text', hint: 'Shown at the bottom of the screen once something is added.' },
      ],
    },
    {
      id: 'c_labels',
      title: 'Column headings & buttons',
      advanced: true,
      variants: ['c'],
      fields: [
        { key: 'c_colProduct', label: 'Product column', type: 'text' },
        { key: 'c_colCategory', label: 'Category column', type: 'text' },
        { key: 'c_colPrice', label: 'Price column', type: 'text' },
        { key: 'c_colQty', label: 'Quantity column', type: 'text' },
        { key: 'c_addButton', label: 'Add button', type: 'text' },
      ],
    },

    // ---- Shared by all layouts ----
    {
      id: 'orderBar',
      title: 'Order bar',
      description: 'The bar at the bottom of the screen showing what is in the order.',
      advanced: true,
      fields: [
        { key: 'checkoutButton', label: 'Checkout button', type: 'text' },
        { key: 'itemSingular', label: 'Item (one)', type: 'text' },
        { key: 'itemPlural', label: 'Items (several)', type: 'text' },
      ],
    },
  ],
  defaults: {
    // Variant A
    a_eyebrow: 'Fine Dining & Takeaway',
    a_title: '{brand}',
    a_rating: '{avgRating}',
    a_reviews: '({reviewCount} reviews)',
    a_cuisine: '{cuisine}',
    a_prepTime: '25-35 min',
    a_prepTimeIcon: 'schedule',
    a_pickup: 'Pickup Available',
    a_pickupIcon: 'shopping_bag',
    a_popularHeading: 'Popular Choices',
    a_popularSubheading: 'Top rated by diners',
    a_sidebarTitle: 'Categories',
    a_searchPlaceholder: 'Search for dishes, drinks, or ingredients...',
    a_filterPopular: 'Popular',
    a_filterVeg: 'Veg',
    a_filterNonVeg: 'Non-Veg',
    a_emptyTitle: 'No dishes found',
    a_emptyText: 'Try adjusting your search query or filter selection.',
    a_cartTitle: 'Selected Gourmet Order',
    a_addButton: 'ADD',
    a_addAnotherAria: 'Add another with options',
    a_shareButton: 'Share',
    a_shareToast: 'Menu link copied to clipboard!',
    a_favoriteButton: 'Favorite',
    a_favoritedButton: 'Favorited',
    a_favoriteAddedToast: 'Added to favorites',
    a_favoriteRemovedToast: 'Removed from favorites',
    // Variant B
    b_eyebrow: 'Weekly Schedule',
    b_title: 'Programs',
    b_searchPlaceholder: 'Search programs...',
    b_cartTitle: 'Selected Sessions',
    b_addButton: 'Book',
    b_sessionCount: '{count} sessions',
    // Variant C
    c_eyebrow: 'Shop',
    c_title: 'Products',
    c_searchPlaceholder: 'Search products...',
    c_allCategories: 'All categories',
    c_emptyText: 'No products match your search.',
    c_cartTitle: 'Cart',
    c_colProduct: 'Product',
    c_colCategory: 'Category',
    c_colPrice: 'Price',
    c_colQty: 'Qty',
    c_addButton: 'Add',
    // Shared
    checkoutButton: 'Checkout',
    itemSingular: 'Item',
    itemPlural: 'Items',
  },
  // Layout A was written for a restaurant; these keep its header strip and wording right for other business types.
  verticalDefaults: {
    gym: {
      a_eyebrow: 'Classes & Coaching',
      a_prepTime: '30-75 min sessions',
      a_prepTimeIcon: 'schedule',
      a_pickup: 'Drop-ins welcome',
      a_pickupIcon: 'group',
      a_popularSubheading: 'Most booked by members',
      a_searchPlaceholder: 'Search classes, programs or coaches...',
      a_emptyTitle: 'No programs found',
      a_cartTitle: 'Selected Sessions',
      a_shareToast: 'Link copied to clipboard!',
    },
    retail: {
      a_eyebrow: 'Shop Online',
      a_prepTime: 'Ships in 2-3 days',
      a_prepTimeIcon: 'local_shipping',
      a_pickup: 'Free pickup in store',
      a_pickupIcon: 'storefront',
      a_popularSubheading: 'Customer favourites',
      a_searchPlaceholder: 'Search products...',
      a_emptyTitle: 'No products found',
      a_cartTitle: 'Your Cart',
      a_shareToast: 'Link copied to clipboard!',
    },
  },
};
