import type { ContentPageDefinition } from '../../types';

export const checkoutContent: ContentPageDefinition = {
  key: 'checkout',
  label: 'Checkout & Order summary',
  description:
    'The page customers see after opening their cart: the order summary, the details form, and the payment step. Prices, taxes and fees are set elsewhere - this only changes the words.',
  previewHash: '#/checkout',
  groups: [
    {
      id: 'summary',
      title: 'Order summary',
      description: 'The left side of the page, listing what is in the cart.',
      fields: [
        { key: 'heading', label: 'Page heading', type: 'text' },
        {
          key: 'subheading',
          label: 'Text under the heading',
          type: 'textarea',
          hint: '{brand} is replaced with your business name.',
        },
        { key: 'backToMenuLabel', label: '"Back to menu" link', type: 'text', hint: 'Shown above the heading and below the order list.' },
        { key: 'addMoreItemsLabel', label: '"Add more items" link', type: 'text' },
        { key: 'itemNoteLabel', label: 'Item note label', type: 'text', hint: 'Shown above the note box under each item.' },
        { key: 'itemNotePlaceholder', label: 'Item note example text', type: 'text', hint: 'Grey example text inside the empty note box.' },
      ],
    },
    {
      id: 'totals',
      title: 'Totals',
      description: 'The price breakdown under the order list.',
      fields: [
        { key: 'subtotalLabel', label: 'Subtotal', type: 'text' },
        { key: 'taxesLabel', label: 'Taxes', type: 'text', hint: '{rate} is replaced with your tax rate, e.g. 8.5.' },
        { key: 'deliveryFeeLabel', label: 'Delivery fee', type: 'text', hint: 'Only shown when the customer chooses delivery.' },
        { key: 'totalLabel', label: 'Total', type: 'text' },
      ],
    },
    {
      id: 'details',
      title: 'Personal details form',
      description: 'The form on the right where customers enter their contact details.',
      fields: [
        { key: 'detailsHeading', label: 'Form heading', type: 'text' },
        { key: 'fullNameLabel', label: 'Name - label', type: 'text' },
        { key: 'fullNamePlaceholder', label: 'Name - example text', type: 'text', hint: 'Grey example text inside the empty box.' },
        { key: 'phoneLabel', label: 'Phone - label', type: 'text' },
        { key: 'phonePlaceholder', label: 'Phone - example text', type: 'text' },
        { key: 'emailLabel', label: 'Email - label', type: 'text' },
        { key: 'emailPlaceholder', label: 'Email - example text', type: 'text' },
        { key: 'addressLabel', label: 'Delivery address - label', type: 'text', hint: 'Only shown when the customer chooses delivery.' },
        {
          key: 'addressPlaceholder',
          label: 'Delivery address - example text',
          type: 'text',
          hint: '{city} is replaced with your area.',
        },
        { key: 'instructionsLabel', label: 'Special instructions - label', type: 'text' },
        { key: 'instructionsPlaceholder', label: 'Special instructions - example text', type: 'text' },
      ],
    },
    {
      id: 'service-payment',
      title: 'Delivery & payment',
      fields: [
        { key: 'serviceLabel', label: 'Service choice heading', type: 'text' },
        { key: 'deliveryOption', label: 'Delivery option', type: 'text' },
        { key: 'pickupOption', label: 'Pickup option', type: 'text' },
        { key: 'paymentMethodLabel', label: 'Payment method heading', type: 'text' },
        { key: 'paymentCardLabel', label: 'Card payment option', type: 'text' },
        { key: 'submitLabel', label: 'Checkout button', type: 'text' },
        { key: 'securityNote', label: 'Security note', type: 'text', hint: 'Shown under the checkout button.' },
      ],
    },
    {
      id: 'payment-step',
      title: 'Payment step',
      description: 'Shown after the customer presses the checkout button and is asked for their card.',
      advanced: true,
      fields: [
        { key: 'securePaymentLabel', label: 'Card payment box heading', type: 'text' },
        { key: 'retryCardLabel', label: '"Try another card" button', type: 'text' },
        { key: 'paymentProcessingNote', label: 'Payment processing message', type: 'textarea' },
        { key: 'verifyingLabel', label: 'Button text while checking', type: 'text' },
        { key: 'successLabel', label: 'Button text when paid', type: 'text' },
      ],
    },
    {
      id: 'messages',
      title: 'Checkout messages',
      description: 'Pop-up and error messages shown during checkout.',
      advanced: true,
      fields: [
        {
          key: 'paymentSuccessToast',
          label: 'Payment successful',
          type: 'textarea',
          hint: '{number} is replaced with the order number.',
        },
        { key: 'addressRequiredToast', label: 'Missing delivery address', type: 'text' },
        { key: 'checkoutStartError', label: 'Could not start checkout', type: 'textarea' },
        { key: 'cardDeclinedError', label: 'Card declined', type: 'textarea' },
        { key: 'paymentPendingError', label: 'Payment still processing', type: 'textarea' },
        { key: 'cardPaymentError', label: 'Card payment failed', type: 'text' },
        { key: 'retryError', label: 'Could not retry payment', type: 'text' },
      ],
    },
    {
      id: 'cart-messages',
      title: 'Cart messages',
      advanced: true,
      fields: [
        {
          key: 'emptyCartToast',
          label: 'Empty cart',
          type: 'text',
          hint: 'Shown when someone tries to check out with an empty cart.',
        },
      ],
    },
    {
      id: 'item-labels',
      title: 'Order item labels',
      description: 'Small labels on each item in the order list.',
      advanced: true,
      fields: [
        { key: 'eachLabel', label: 'Price per item', type: 'text', hint: '{price} is replaced with the price of one item.' },
        { key: 'removeItemTitle', label: 'Remove item - tooltip', type: 'text' },
        { key: 'removeAddonTitle', label: 'Remove add-on - tooltip', type: 'text' },
        {
          key: 'removeItemAriaLabel',
          label: 'Remove item - screen reader label',
          type: 'text',
          hint: '{name} is replaced with the item name. Read aloud by screen readers.',
        },
        {
          key: 'removeAddonAriaLabel',
          label: 'Remove add-on - screen reader label',
          type: 'text',
          hint: '{name} is replaced with the add-on name.',
        },
        { key: 'decreaseAriaLabel', label: 'Decrease quantity - screen reader label', type: 'text', hint: '{name} is replaced with the item name.' },
        { key: 'increaseAriaLabel', label: 'Increase quantity - screen reader label', type: 'text', hint: '{name} is replaced with the item name.' },
      ],
    },
  ],
  defaults: {
    heading: 'Order Summary',
    subheading: "Review your selection of {brand}'s finest offerings.",
    backToMenuLabel: 'Back to Menu',
    addMoreItemsLabel: 'Add More Items',
    itemNoteLabel: 'Item note',
    itemNotePlaceholder: 'e.g. no onions, extra spicy...',

    subtotalLabel: 'Subtotal',
    taxesLabel: 'Taxes ({rate}%)',
    deliveryFeeLabel: 'Delivery Fee',
    totalLabel: 'Total',

    detailsHeading: 'Personal Details',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'Julian Vane',
    phoneLabel: 'Phone Number',
    phonePlaceholder: '+44 20 7123 4567',
    emailLabel: 'Email Address',
    emailPlaceholder: 'julian.v@example.com',
    addressLabel: 'Delivery Address',
    addressPlaceholder: '14 {city} Square, London, W1J 8AJ',
    instructionsLabel: 'Special Instructions',
    instructionsPlaceholder: 'Dietary restrictions or delivery notes...',

    serviceLabel: 'Service Preference',
    deliveryOption: 'Delivery',
    pickupOption: 'Pickup',
    paymentMethodLabel: 'Payment Method',
    paymentCardLabel: 'Credit Card',
    submitLabel: 'Proceed to Secure Checkout',
    securityNote: 'Your transaction is secure and encrypted.',

    securePaymentLabel: 'Secure card payment',
    retryCardLabel: 'Retry with another card',
    paymentProcessingNote: 'Payment processing. This page will update when Finix confirms the result.',
    verifyingLabel: 'Verifying...',
    successLabel: 'Success',

    paymentSuccessToast: 'Payment successful. Order #{number} is awaiting restaurant acceptance.',
    addressRequiredToast: 'Please enter a delivery address.',
    checkoutStartError: 'Something went wrong starting checkout. Please try again.',
    cardDeclinedError: 'Your card was declined. You can retry with another card.',
    paymentPendingError: 'Your payment is still processing. Please keep this page open and check again shortly.',
    cardPaymentError: 'Unable to process the card payment.',
    retryError: 'Unable to retry this payment.',

    emptyCartToast: 'Add items to your cart before checkout.',

    eachLabel: '{price} each',
    removeItemTitle: 'Remove item',
    removeAddonTitle: 'Remove add-on',
    removeItemAriaLabel: 'Remove {name}',
    removeAddonAriaLabel: 'Remove {name}',
    decreaseAriaLabel: 'Decrease {name}',
    increaseAriaLabel: 'Increase {name}',
  },
  verticalDefaults: {
    gym: {
      backToMenuLabel: 'Back to Programs',
      addMoreItemsLabel: 'Add More Sessions',
      paymentSuccessToast: 'Payment successful. Order #{number} has been sent to the studio.',
    },
    retail: {
      backToMenuLabel: 'Back to Shop',
      addMoreItemsLabel: 'Add More Products',
      paymentSuccessToast: 'Payment successful. Order #{number} has been sent to the shop.',
    },
  },
};
