import { http, HttpResponse } from 'msw';

// No audit log entries are generated by the mock backend yet (stretch scope);
// the endpoint exists so the frontend's Audit Log screen has a real contract to call.
export const auditLogHandlers = [
  http.get('*/api/v1/restaurants/:id/audit-logs', () =>
    HttpResponse.json({ items: [], total: 0, page: 1, pageSize: 20 }),
  ),
];
